# Generated by Django 3.0.7 on 2020-08-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realers',
            options={'verbose_name_plural': 'Realers'},
        ),
        migrations.AlterField(
            model_name='realers',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
