# Generated by Django 3.0.7 on 2020-08-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realers', '0002_auto_20200801_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realers',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
