# Generated by Django 3.0.7 on 2020-08-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realers', '0003_auto_20200801_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realers',
            name='top_seller',
            field=models.BooleanField(default=False),
        ),
    ]
