# Generated by Django 3.0.7 on 2020-08-01 13:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realers', '0004_auto_20200801_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
                ('descritption', models.TextField(blank=True)),
                ('sale_type', models.CharField(choices=[('for sale', 'For Sale'), ('for rent', 'For Rent')], default='for sale', max_length=50)),
                ('price', models.IntegerField()),
                ('bedroom', models.IntegerField()),
                ('bedrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('home_type', models.CharField(choices=[('house', 'House'), ('congo', 'Congo'), ('town house', 'Townhouse'), ('lodge', 'Lodge'), ('land', 'Land')], default='house', max_length=50)),
                ('sqft', models.IntegerField()),
                ('open_house', models.BooleanField(default=False)),
                ('photo_main', models.ImageField(upload_to='photo/%Y/%m/%d/')),
                ('photo1', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('photo2', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('photo3', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('photo4', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('photo5', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('photo6', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('photo7', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('photo8', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('photo9', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('photo10', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('photo12', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('photo13', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('photo14', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('photo15', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('photo16', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('photo17', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('photo18', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('photo19', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('photo20', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('realter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realers.Realers')),
            ],
        ),
    ]
