# Generated by Django 3.1 on 2020-09-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='descritption',
            new_name='description',
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='home_type',
            field=models.CharField(choices=[('House', 'House'), ('Congo', 'Congo'), ('Town House', 'Townhouse'), ('Lodge', 'Lodge'), ('Land', 'Land')], default='House', max_length=50),
        ),
    ]
